apiVersion: v1
kind: Secret
metadata:
   name: env-corporate-service-secret
type: Opaque
data:
   POSTGRES_USERNAME: cG9zdGdyZXM=
   POSTGRES_PASSWORD: Y3V5TlB1dFAyZkwxOWhnYw==
   REDIS_PASSWORD: XCJZdGNTRkhmKmtLJDZWUQ==
   STATIC_AUTH: M0lkNkd1UUZySWZDMUFQTWJ5MG5qekZrOE9SU2pBU0dMRTVFY3Roam1jSEdvZ1ZPNVlCQTNROWFIaUlDWnJGTw==
   MJ_APIKEY_PUBLIC: ZWIwMzdiYWNkMTVhZGY5MTI0MDYwYzYwMmI1YjM1OWY=
   MJ_APIKEY_PRIVATE: MmFlZGU0NGJlZmY4OGI4ZWFiZTVkNTcxNDE1NzJmYWQ=